web:
  build: ./web
  ports:
    - "3600:3600"
  volumes:
    - ./code/web:/srv/www/sandbox
  command: bash -c "cp /srv/www/sandbox/package.json /srv/www/ && cd /srv/www && npm install && node /srv/www/sandbox/server.js"
  links:
    - mongodb
mongodb:
  image: mongo
  ports: 
   - "27017:27017"
  environment:
    MONGODB_PASS: password