sandbox:
  build: ./config
  ports:
    - "3600:3600"
  volumes:
    - ./code/sandbox:/srv/www/sandbox
  command: bash -c "cd /srv/www/sandbox && npm install && node /srv/www/sandbox/server.js"
  links:
    - mongodb
front:
  build: ./config
  ports:
    - "3333:3333"
  volumes:
    - ./code/front:/srv/www/front
  command: bash -c "cd /srv/www/front && npm install && node /srv/www/front/src/index.js"
  links:
    - mongodb
mongodb:
  image: mongo
  ports:
   - "27017:27017"
  environment:
    MONGODB_PASS: password